name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: "install"
        run: npm install

      - name: "publish"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
